### signUp
POST http://localhost:4001/users/signUp HTTP/1.1
content-type: application/json

{
    "user_id": "chojs",
    "user_password": "1234", 
    "user_password_confirm": "1234",
    "like_list": ["1021", "1034", "12"]
}

### push likeList
POST http://localhost:4001/users/likeList/push HTTP/1.1
content-type: application/json

{
    "user_id": "chojs",
    "content_id": "1021"
}

### pop likeList
POST http://localhost:4001/users/likeList/pop HTTP/1.1
content-type: application/json

{
    "user_id": "chojs",
    "content_id": "1"
}

### getUserInfo
GET http://localhost:4001/users/userInfo?user_id=chojs HTTP/1.1

